### PR TITLE
Add initial simple healthbar

### PR DESCRIPTION
**Pull request by Roynecro97**
Not addressing issues because the iPhone’s interface makes it too hard.
Need to make it run in a thread to allow cool animations.

### CODE REVIEW

**Comment by GuyOded** [comment]
Improvement suggestion - migrate to python packages (add __init__, separate the concrete from the base to different files.

**Comment by Roynecro97** [comment]
This is a python package, `__init__.py` is optional in python3 and only needed in some cases.
The base file has the base health bars while other files will have animations (then I’ll probably add an init file to hide the modules).

**Comment by GuyOded** [comment]
The ConsoleHealthbar is an implementation of the base, abstract, healthbar to my understanding. Thus, I would suggest moving it to a different file.

**Comment by Roynecro97** [comment]
I don’t see any reason to separate them (the LED one should be here too imo), it’s not the abstract base health bar’s implementation, its the basic implementation. Too many modules just get harder to manage.

**Pull request merged**
